%%{init: {'theme':'forest'}}%%
sequenceDiagram
    box executor group
    Participant Dispatcher
    Participant Executor
    end
    Participant db-workflows
    Participant db-workflow_next_execution
    Participant db-workflow_in_progress
    Dispatcher->>db-workflow_next_execution: get pending
    db-workflow_next_execution-->>Dispatcher: -
    Dispatcher->>db-workflow_running: -
    note over db-workflow_running: this can be run many times
    db-workflow_running-->Dispatcher: -
    Dispatcher->>db-workflow_next_execution: LWT Delete
    note over db-workflow_next_execution: only one gets this run
    db-workflow_next_execution-->>Dispatcher: -
    note over Dispatcher: if dispatcher crashes here, maintainer can find and fix
    Dispatcher->>Executor: start workflow
    Executor->>db-workflow_in_progress: write
    db-workflow_in_progress-->>Executor: -
    alt run
     Executor->>db-workflows: set IN_PROGRESS
     Executor->>Executor: run workflow methods
     Executor->>db-workflows: update workflow variables
     Executor->>Executor: run workflow methods
     Executor->>db-workflow_in_progress: delete
    end

    db-workflow_in_progress-->>Executor: -
    Executor->>db-workflow_running: delete
    db-workflow_running-->>Executor: -
    alt maintainer
    Dispatcher->>db-workflow_running:find stuck tasks older than time
    db-workflow_running-->>Dispatcher: -
    end

